### ISSUE TITLE
Add support for license.md

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/flutter-icapps-license#1]
Add support for license.md

**Comment by ThichLaNhich88** [comment]
License.md

**Comment by ThichLaNhich88** [comment]
https://github.com/icapps/flutter-icapps-license/issues/1#issue-546824390

**Comment by vanlooverenkoen** [comment]
@ThichLaNhich88 do you have package where license.md is used? So I can test this?

**Comment by vanlooverenkoen** [comment]
This will be implemented in the full refactor

**Comment by vanlooverenkoen** [comment]
This is included in our new package license_generator. It is released with version: 1.0.0
