### ISSUE TITLE
Add support for GitLab (or other repos)

### ISSUE THREAD

**Issue by Arokip** [icapps/flutter-icapps-license#22]
Currently this package supports licenses which are stored on GitHub but not eg. GitLab. Some packages from pub.dev has a repository and therefore also the license file on GitLab or other platforms.

The licenses on GitLab are stored in `/blob/main/LICENSE` directory.

**Comment by vanlooverenkoen** [comment]
Could you give me some examples? I am working on a full refactor. Where we can easily support other repo's as well

**Comment by Arokip** [comment]
Currently, I have just one example with open project. Other private projects have same relative url on gitlab. The license is located here: https://gitlab.com/famedly/company/frontend/famedlysdk/-/blob/main/LICENSE

**Comment by vanlooverenkoen** [comment]
Alright thanks. I will pick that up today as well. I expect the new license_generator (renamed) to be released next week

**Comment by vanlooverenkoen** [comment]
I will create a seperate pr so you can review it without the full refactor

**Comment by vanlooverenkoen** [comment]
This is included in our new package license_generator. It is released with version: 1.0.0
