### ISSUE TITLE
Add an option to save the license.dart file in another directory

### ISSUE THREAD

**Issue by Arokip** [icapps/flutter-icapps-license#23]
Currently the `license.dart` file is saved in `/util` directory.

It would be nice to add an option to save it to user defined directory.

**Comment by vanlooverenkoen** [comment]
This will be included in the full refactor. you will be able to set your file output path with `output_path`

**Comment by vanlooverenkoen** [comment]
This is included in our new package license_generator. It is released with version: 1.0.0
